### ISSUE TITLE
Preferred diagramming tool/format

### ISSUE THREAD

**Issue by NOP0** [Michael-F-Bryan/rustmatic#32]
In time I would like to try contributing some diagrams. Of course I would like to use a format/tool that is editable by others. Is there any preferred tool/format?

**Comment by Michael-F-Bryan** [comment]
Not really. What works for you?

**Comment by NOP0** [comment]
I've used https://www.draw.io/ some in the past, but I'm not married to it. :wink:

**Comment by Michael-F-Bryan** [comment]
I've also used it in the past when needing to explain/document complicated things like state machines or network diagrams. I've found it works pretty well. 

[mermaid.js](https://mermaidjs.github.io/) is also pretty good when it comes to flow charts, especially when you just want to say "X connects to Y" and have the computer figure out where to place everything.

**Comment by NOP0** [comment]
Hey, hadn't heard of mermaid.js, nice. 
We have some suggested tools then, closing this.

**Comment by NOP0** [comment]
Suggested tools; draw.io,  mermaid.js
